export const title="China's Brutal Road to Socialism";
export const date=new Date('May 23, 2022'); //published date
import { P, Citation, Footnote, HangingIndent } from '../Components';
import Link from 'next/link';
import Image from 'next/image';

export default function ChinasBrutalRoadToSocialism() {
    return <div>
        {/* TODO: footnotes */}
        <h3 id='introduction'>Introduction</h3>
        <Character name='huá' />
        <P>The Great Leap Forward and Cultural Revolution were disasters because they caused tremendous human suffering for too little gain. They killed and purged tens of millions and ruined the lives of countless innocent intellectuals and businessmen. In 1949, the Chinese Communist Party (CCP) conquered mainland China and declared the People’s Republic of China. They initially followed the Soviet Union’s example of moving to a utopian communist society with socialism as an intermediary state. However, the CCP’s leader, Mao Zedong, made China’s path to communism different from the Soviet Union’s due to China’s different demographics and cultures. Mao instigated two major events during the tumultuous period of 1958 to 1972: the Great Leap Forward and Cultural Revolution. The events liberated China from foreign control and formed the foundation for a stable country that would outlast the Soviet Union. However, they resulted in widespread, unjust violence. All things considered, the communists caused too much human suffering to transform China into a stable and independent socialist superpower during the Great Leap Forward and Cultural Revolution.</P>
        
        <h3 id='section-1'>Ⅰ. The Great Leap Forward</h3>
        <Character name='yuè' />
        <P>The Great Leap Forward helped China industrialize, become more independent, and increase the masses’ faith in the government, but the CCP’s irresponsibility during the famine revealed their indifference toward the people’s suffering. The CCP’s unique implementation of the Great Leap Forward moved China away from relying on the Soviet Union’s guidance. The Great Leap Forward improved people’s faith in the government by giving the impression that government officials cared for them through the hardships. However, the policies failed due to the CCP’s misplanning in trying to grow China’s economy unrealistically quickly. Low agricultural production held back the Chinese economy and caused famine. Instead of revising policy or sending farmers aid, the CCP refused to admit that its policies were failing. Tens of millions of peasant farmers unnecessarily starved to death only because the CCP was unwilling to admit its failure. Although growing China’s independence and people’s faith in the government, the CCP lacked valid justification for the deaths and suffering caused by the Great Leap Forward.</P>
        <P>The CCP’s impatience to grow China caused the Great Leap Forward’s famine by increasing food needs too quickly. The CCP combined private farms into joint farms called communes, whose yields were aggregated and distributed back.<Citation number='1' /> The movement led to the horrendous Great Chinese Famine, killing an estimated twenty million people from 1959 to 1962.<Citation number='2' /> Indeed, bad weather and natural disasters contributed to the low food yields.<Citation number='3' /> Nevertheless, the CCP was responsible for the famine’s deaths and suffering because of its misplanning and negligent response to the crisis. Before the crisis, the CCP should have considered bad weather when planning; during the crisis, the CCP should have lowered its extreme goals and prioritized feeding the population. The origins of the CCP’s misplanning can be traced back to Mao’s belief that the masses could accomplish anything quickly when organized together.<Citation number='4' /> Mao illustrated his urge for China to compete with the rest of the world with his slogan, “Overtake England in fifteen years!”<Citation number='5' /> In order to meet Mao’s unreachable goal of quickly surpassing England’s industrial might, the CCP planned to distribute food to too many sources. Instead of just feeding the farmers, the CCP needed to distribute food to the new urban workers and the Soviet Union as payment for their industrializing aid.<Citation number='6' /> Moreover, the Great Leap Forward made farmers work on infrastructure during their previously idle seasons, making all their seasons busy.<Citation number='7' /> Since peasant farmers ate three to four times more food during busy seasons than idle seasons, overworked peasant farmers also needed more food to work on infrastructure.<Citation number='8' /> The CCP’s price for industrializing was a high, unattainable food demand. The CCP’s misplanning caused the famine by setting up high food needs that the communes could not meet.</P>
        <P>In addition to increasing the need for food, the CCP’s policies reduced the food yield, showing the CCP’s incompetence and inability to correct its mistakes. Although the CCP created the Great Leap Forward to expand production, grain production shrank 13% during the campaign.<Citation number='9' /> Communes created extreme policies that failed, such as sowing seeds three feet deeper into the soil since digging one foot deeper had helped past yields or creating steel in backyard furnaces in hopes of speeding up industrialization.<Citation number='10' /> The extremity of their policies showed that the government was too impatient to increase yields. Since most of the steel was unusable, backyard furnaces were an unproductive use of the farmers’ time and energy.<Citation number='11' /> Farmers followed governmental instructions such as digging three feet deep, not what they knew was best. Organizing society into communes lowered the food yields because farmers followed the government’s country-wide instructions, not what they knew was best for their specific land. Even though the communes continued to produce insufficient amounts of food, Mao could not backtrack on his policies because doing so would be admitting that he had erred, causing the people to lose faith in his governing abilities. His inability to backtrack on his policies demonstrated a problem of giving one person immense power as the CCP did. Separately, how much food an individual farmer produced did not affect how much they received during government redistribution. As a result, farmers were not incentivized to work other than out of patriotism or to satisfy the government, further contributing to the low yields. The policies’ failure showed the problems of the centralized economic structure the CCP set up.</P>
        <P>However, the Great Leap Forward was not a complete failure: the Great Leap Forward made China more independent from the Soviet Union. As Sino-Soviet tensions increased, the Soviet Union became less reliable. One reason for increased tensions was Khrushchev’s de-Stalinization campaigns that denounced the idolatry of Stalin.<Citation number='12' /> Since Mao Zedong emulated Stalin’s cult of personality, Khruschev indirectly discouraged the Chinese people from idolizing Mao, threatening the CCP. Additionally, the Chinese and Soviet communists had ideological conflicts. Mao wanted to prepare to challenge the capitalist West, while Khruschev believed in peaceful coexistence.<Citation number='13' /> The disputes resulted in the Soviet Union pulling out its scientists who were helping China build a nuclear bomb and technicians who were planning Chinese factories.<Citation number='14' /> Although Soviet scientists helped China develop, China gained independence by refusing to concede to the Soviet interpretation of communism and sacrificing their help. Without Soviet aid, China successfully created and tested its bombs.<Citation number='15' /> The CCP’s bomb testing meant China was no longer dependent on the Soviet Union’s bomb deterrence. More generally, it signified China’s lack of reliance on the Soviet Union thereafter. Until this point, China had learned most of its socialist doctrine from the Soviet Union’s implementation. After that point, China proved that it did not need the Soviet Union’s support and would create its own interpretation of socialism. Increasing independence and reducing foreign reliance made China more of a superpower able to stand up for itself.</P>
        <P>Furthermore, the Great Leap Forward boosted faith in the CCP because government officials were perceived to care for the masses. Politicians worked in the fields among farmers and ate like everyone else.<Citation number='16' /> This political structure was part of the mass line, Mao’s approach to organizing government so that policies were closely linked to the masses.<Citation number='17' /> Mao made it seem like he appreciated farmers by sending artists to perform in their fields.<Citation number='18' /> Being in the national spotlight, the farmers had high morale because they felt important and appreciated by the government and society. Even when crop yields decreased and farmers starved during the Great Chinese Famine, they did not rebel because they approved of the government. When officials accused the Great Leap Forward of causing starvation, Mao tried to justify the alleged deaths in the communes: “If seventy percent collapsed, there would still be thirty percent left. If they must collapse, let them.”<Citation number='19' /> Although the government gave the impression that it cared for the farmers’ lives, Mao was less concerned with the farmers’ lives than increasing yields in the Great Leap Forward. Due to the government’s perceived focus on the farmer’s well-being, the masses gained faith in the government.</P>
        
        <h3 id='section-2'>ⅠⅠ. The Cultural Revolution</h3>
        <Character name='gé' />
        <P>The Great Proletarian Cultural Revolution, more like the Cult of Mao Revolution, ruined lives, brainwashed the youth, and destroyed tradition to keep Mao in power. The Cultural Revolution’s two main goals were strengthening the CCP’s control and moving China closer to communism by revitalizing the revolution. While it successfully enforced the communists’ control over the population, it failed to preserve the communist ideology because Deng introduced capitalism ten years later. Destroying dissent to maintain control cost the communists their popular legitimacy and China its independent thinking.</P>
        <P>Even though terrorizing the population consolidated the CCP’s power, the Cultural Revolution failed by losing the government its legitimacy and popular trust. The Cultural Revolution caused people to live in fear. The Hundred Flowers Campaign from 1956 to 1957 encouraged people to speak freely about their feelings toward the government.<Citation number='20' /> However, during the Cultural Revolution a decade later, Mao purged those who had spoken out and encouraged the youth to purge rightists.<Citation number='21' /> Even former communists were not spared. Liu Shaoqi, the Chairman of the CCP; Peng Zhen, the mayor of Peking; and Peng Dehuai, Mao’s defense minister, were all betrayed, humiliated, and tormented because they had criticized Mao.<Citation number='22' /> People trusted the government less because Mao went back on his word and chose to rule with fear. Any communist could be purged for saying something deemed counter-revolutionary, so communists feared the CCP. The result of a society ruled by fear was the idolization of Mao. One reason people wanted to show their allegiance to Mao was to avoid being targeted. The cost of controlling China through fear was a loss of legitimacy. Whereas the early CCP wanted to ensure the proletariat’s well-being, the new party lost its old legitimacy and compassion towards commoners by purging even its own members.</P>
        <P>The Cultural Revolution scared people from criticizing the communists, securing the CCP’s control. Not only did Mao suppress thoughts from the Hundred Flowers Campaign that went directly against communism, but he also censored innocent independent thinkers such as teachers and scientists because they had the best ability to criticize him and threaten his control. Intellectuals were sent to brutal reeducation camps to do forced manual labor.<Citation number='23' /> One of my great-grandfathers, Chen Zhongliang, was sent to these camps to do labor-intensive farming, sleep in a run-down cowshed, study the Little Red Book, and fabricate a confession about being a rightist bourgeoisie. By forcing intellectuals to do unpleasant manual labor, read about Mao, and testify against their previous beliefs, these camps scared any intellectuals from criticizing the communists. As if that is not enough, purged people were publicly humiliated in parades for hours.<Citation number='24' /> Mistreatment of anyone who allegedly opposed the CCP was displayed to the public so that people knew the consequences of resisting the CCP. The CCP justified the Cultural Revolution by alleging that it liberated the masses, but in reality, they were terrorizing the population into submission.</P>
        <P>Suppressing independent thinking through fear did more harm than good by reducing China’s brainpower and the CCP’s ability to assess and execute policies fairly. First, China lost brainpower by purging scientists, intellectuals, and teachers. Before the revolution, pupils respected their teachers, like Confucius’ disciples respected him. However, during the Cultural Revolution, the Red Guard attacked teachers, intellectuals, and anyone who tried to stop them.<Citation number='25' /> Many did not want to become intellectuals, whom the Red Guard targeted. Second, without anyone being allowed to criticize the CCP’s plan, the CCP’s mistakes were left unchecked. When the CCP equivocated, communist leaders did not correct their mistakes, lest they give the impression that their decisions were illegitimate, and the people usually did not say anything against the policy because they feared punishment for disloyalty. China needed intellectuals to develop its society, so attacking Chinese intellectualism was a mistake. The communists should have consolidated their power by appealing to the Chinese intellectuals’ reasoning instead of terrorizing them into submission.</P>
        <P>Despite purging tens of millions for the cause, the Cultural Revolution was unable to achieve its goal of keeping capitalism out of China. Besides consolidating Mao and the CCP’s power, the point of the Cultural Revolution was to remove capitalists, revisionists, and other rightist thinkers, so their policies did not take control of China. However, only a decade later, Deng Xiaoping introduced revisionist, capitalist policies.<Citation number='26' /> It was pointless and wrong to ruin tens of millions of innocent Chinese lives to keep out capitalism only to accept the ideology a decade later. The suffering caused by the Cultural Revolution was a waste, not for China’s greater good.</P>

        <h3 id='section-3'>Conclusion</h3>
        <Character name='zōng' />
        <P>China could have transformed into a superpower with less human suffering. Much of the suffering during the Great Leap Forward and Cultural Revolution was unnecessary in developing China because it was centered around loyalty to the party. As a result, hypersensitivity around being loyal to the party caused problems. The communists’ fear of questioning Mao and the CCP’s authority caused starvation during the Great Leap Forward. The masses’ loyalty to Mao did not lead Mao to help them back: by allowing farmers to starve on his watch, Mao prioritized his authority over his subjects’ suffering. Likewise, the Cultural Revolution’s purging of intellectuals was caused by the government’s desire to secure its power in society. Instead of scaring them into insincere obedience, the CCP should have given intellectuals a reason to like their rule.</P>
        <P>Notwithstanding the atrocities, the Great Leap Forward and Cultural Revolution had long-term benefits by founding a more patriotic, independent, and stable nation. China grew and set up the path for a stronger future from 1958 to 1972. By the end of this period, China was becoming a global superpower. The United Nations sent a delegation to China in 1971, showing China’s international recognition.<Citation number='27' /> Moreover, Nixon visited China in 1972, and China signed deals with Western nations.<Citation number='28' /> China was no longer a fractured nation plagued by civil war nor a weak Qing dynasty but instead a unified country ruled by a strong central government.</P>
        <P>Knowledge of twentieth-century Chinese history is integral to understanding China’s stance in the world as a global superpower today. For example, China’s current zero-COVID policy resembles the Great Leap Forward in three ways. First, both campaigns espoused extreme policies: the Great Leap Forward required people to dig three feet deep and work during the idle seasons, and the zero-COVID policy prevents entire cities’ populations from leaving their houses for long amounts of time. Second, the CCP does not allow criticism of the zero-COVID policy, similar to how it did not tolerate “rightist” thinking during the Cultural Revolution. Third, the zero-COVID policy is associated with Xi Jinping, similar to how the Great Leap Forward and Cultural Revolution were associated with Mao. As with Mao, Xi cannot revise or revoke his policy without going against his previous decisions and questioning his authorities’ legitimacy. The CCP is making the same mistakes in the zero-COVID policy that it made in the Great Leap Forward and Cultural Revolution. Remnants of the Great Leap Forward and Cultural Revolution live on today in the CCP and Chinese life.</P>

        <h3 className='text-center' id='footnotes'>Footnotes</h3>
        <Footnote number='1'>Jonathan D. Spence, <i>The Search for Modern China</i>, 2nd ed. (New York: W. W. Norton & Company), 549.</Footnote>
        <Footnote number='2'>Alexander Eckstein, <i>China’s Economic Revolution</i> (Riverdale Country School Boocock Library: Cambridge University Press), 202.</Footnote>
        <Footnote number='3'> Spence, 553.</Footnote>
        <Footnote number='4'>Stuart Schram, <i>The Thought of Mao Tse-Tung</i> (New York: Cambridge University Press), 113.</Footnote>
        <Footnote number='5'>Ibid., 131.</Footnote>
        <Footnote number='6'>Spence, 545.</Footnote>
        <Footnote number='7'>Han, 23.</Footnote>
        <Footnote number='8'>Ibid.</Footnote>
        <Footnote number='9'>Eckstein, 210.</Footnote>
        <Footnote number='10'>William Hinton, “On the Role of Mao Zedong,” 4. Retrieved from <Link href='https://monthlyreview.org/2004/09/01/on-the-role-of-mao-zedong' target='_blank'>monthlyreview.org/2004/09/01/on-the-role-of-mao-zedong</Link>; Han, 20.</Footnote>
        <Footnote number='11'>Eckstein, 202.</Footnote>
        <Footnote number='12'>Spence, 539.</Footnote>
        <Footnote number='13'>Ibid., 555.</Footnote>
        <Footnote number='14'>Ibid., 558.</Footnote>
        <Footnote number='15'>Ibid., 567.</Footnote>
        <Footnote number='16'>Donping Han, “Farmers, Mao, and Discontent in China,” 26. Retrieved from monthlyreview.org/2004/09/01/on-the-role-of-mao-zedong.</Footnote>
        <Footnote number='17'>Xing Li, “The Chinese Cultural Revolution Revisited,” 149. Retrieved from www.jstor.org/stable/23461931.</Footnote>
        <Footnote number='18'>Han, 26.</Footnote>
        <Footnote number='19'>Spence, 552.</Footnote>
        <Footnote number='20'>Ibid., 539.</Footnote>
        <Footnote number='21'>Ibid., 542-3.</Footnote>
        <Footnote number='22'>Ibid., 573.</Footnote>
        <Footnote number='23'>Ibid., 582.</Footnote>
        <Footnote number='24'>Ibid., 575.</Footnote>
        <Footnote number='25'>Ibid., 575-6.</Footnote>
        <Footnote number='26'>Ibid., 621.</Footnote>
        <Footnote number='27'>Ibid., 596.</Footnote>
        <Footnote number='28'>Ibid., 589.</Footnote>
        <br />

        <h3 className='text-center' id='bibliography'>Bibliography</h3>
        <HangingIndent>Eckstein, Alexander. <i>China’s Economic Revolution</i>. Riverdale Country School Boocock Library: Cambridge University Press, 1977.</HangingIndent>
        <HangingIndent>Han, Donping. “Farmers, Mao, and Discontent in China,” <i>Monthly Review</i> 61.7 (Dec 2009): 20-36, <Link href='https://docs.google.com/a/riverdale.edu/file/d/0B8oWua-vbzW0RmpVajFwYVJYdGM' target='_blank' className='styled'>docs.google.com/a/riverdale.edu/file/d/0B8oWua-vbzW0RmpVajFwYVJYdGM</Link>.</HangingIndent>
        <HangingIndent>Hinton, William. “On the Role of Mao Zedong.” <i>Monthly Review</i>, no. 4 (Sept 2004): 50-59, <Link href='https://monthlyreview.org/2004/09/01/on-the-role-of-mao-zedong' target='_blank' className='styled'>monthlyreview.org/2004/09/01/on-the-role-of-mao-zedong</Link>.</HangingIndent>
        <HangingIndent>Li, Xing. “The Chinese Cultural Revolution Revisited.” <i>China Review</i>, no. 1 (2001): 137–65, <Link href='https://www.jstor.org/stable/23461931' target='_blank' className='styled'>www.jstor.org/stable/23461931</Link>.</HangingIndent>
        <HangingIndent>Schram, Stuart. <i>The Thought of Mao Tse-Tung</i>. New York: Cambridge University Press, 1989.</HangingIndent>
        <HangingIndent>Spence, Jonathan D. <i>The Search for Modern China</i>, 2nd ed. New York: W. W. Norton & Company, 1999.</HangingIndent>
    </div>;
}

function Character({ name }: { name: string }) {
    return <Image
        src={`/image/perspective/chinas-brutal-road-to-socialism/${name}.jpg`} title={name} alt={`Calligraphic character for ${name}`}
        width={30} height={30}
        style={{
            position: 'absolute'
        }}
    />;
}
