import ArticleWrapper from '@/components/blog/ArticleWrapper';
import { P } from '@jcomponents/writing-components';

export default function ConnectingWithThePast() {
    return <ArticleWrapper title='Connecting with the Past' date={new Date('Aug 10, 2021')} hyphenatedTitle='connecting-with-the-past'>
        <P>Humans of the last 10,000+ years share almost identical minds and bodies, differing only by their surroundings. If you and a caveman baby switched places at birth, I believe you would integrate into the caveman family just like any caveman baby does, and the caveman baby would fit into modern society just like any modern baby. The caveman baby would grow up accustomed to airplanes, cars, electricity, computers, and supermarkets, while you would spend the day hunter-gathering and salivating at the thought of raw vegetables. Much of a population&apos;s lifestyle is determined by surrounding conditions, which change dramatically, far more quickly than human DNA evolves. Nearly all of human progress over the centuries has been in the society (ideas, values, norms, institutions, social constructs, infrastructure, physical items) that all its member humans take from and contribute to, not in the construct of the human individual.</P>
        <P>When studying people from any past era, we can empathize and connect more by keeping in mind they are fundamentally the same as us, only existing in vastly different circumstances. When reading textbooks that make them seem alien, it is important to remember they were what we would have been too in their shoes and to treat their lives as if they were our lives. For example, commoners in a Middle-Age fiefdom never left the few-mile radius around their settlement for their entire lives and their quality of life by our standards was inferior. Even though today I would be driven crazy if I never explored the world outside my local community and didn’t have balanced, healthy meals and freshly laundered clothes, that would be the life I expected and was accustomed to. Although it certainly doesn’t sound appealing, I can imagine waking up to put on their smelly shoes and eating breakfast of stale bread and porridge.</P>
    </ArticleWrapper>;
}
