import ArticleWrapper from '@/components/blog/ArticleWrapper';
import { P } from '@jcomponents/writing-components';
import Image from 'next/image';

export default function MindfullyTravelingToSchool() {
    return <ArticleWrapper title='Mindfully Traveling to School' date={new Date('Nov 11, 2021')} hyphenatedTitle='mindfully-traveling-to-school'>
        <Image src='/image/blog/mindfully-traveling-to-school/Biking to School square.jpg' alt='Biking to School' width='250' height='242' style={{ float: 'right', marginLeft: 20 }} />
        <P>On a clear November morning last fall, I decided to bike and walk the 15 miles to school instead of taking the usual school bus. A Riverdale assembly speaker shared her story of walking across the United States a few years ago, and I was similarly curious to observe what was along the way that I typically ignore on my trip to school.</P>
        <P>I left home from the Financial District, the southern tip of Manhattan, packing my bag earlier than usual after reassuring my parents that I would be safe. I had wanted to do this two years earlier, but they insisted I was too young. I biked along the Hudson River, watching the rising sun and flow of the river. A group of ducks quacked while flying into the water, and leaves fell gracefully into sheets of orange, pink, and red covering the ground. After a while, I stopped to rest on a bench. The calm breeze and beauty of the rising sun made me joyful and at ease, a change from being immersed in busy student life.</P>
        <P>The Hudson River bike path kept changing, from wide to narrow, gravel to cement, along the highway to under a bridge, and in the trees to near the water. To the left was the Hudson River, and on the other side, a river of vehicles. Occasionally, I saw yellow school buses zip by on the highway and thought about my classmates inside.</P>
        <P>Reaching the end of the bike path after an hour and fifty minutes, I returned the Citi bike and walked the rest of the way. I passed through a primarily Dominican neighborhood with decorations remaining from the Day of the Dead, brownstones, and churning laundromats. I observed parts of the city I had never seen before. Every block had its own personality. Some were bustling with vehicles, while others were quieter with a few parked cars. Some streets shined with fresh paint, while others had graffiti and smelled bad. Mom-and-pop stores dotted the streets, a pleasant change from the big chains I am used to. By the time I entered Fieldston Road, I was so excited to be approaching Riverdale. Large houses surrounded by fallen leaves lined the roads, and greenery filled the parks. Finally, I entered the campus gates.</P>
        <P>It felt surreal wandering around school, just like any other day. I looked at the campus differently. Living far from school, I had considered Riverdale and my neighborhood separate worlds since at home I rarely run into someone from school. Experiencing what lay between the worlds connected them in my mind.</P>
        <P>The journey had additional after-effects. Three hours of traveling in solitude made me feel more self-sufficient because I did not need a driver to travel to school. Afterward, I felt surprisingly energized, not tired. Perhaps the new experiences gave me vigor. Traveling fifteen miles by myself even made me more mindful of my place in the universe. I will never complain again about walking from 9/10 to Lindenbaum.</P>
        
        <br /><br />
        <Image src='/image/blog/mindfully-traveling-to-school/Map.jpg' alt='Map' width='110' height='378' />
    </ArticleWrapper>;
}
