import ArticleWrapper from '@/components/blog/ArticleWrapper';
import { P } from '@jcomponents/writing-components';

export default function ReflectionOnPrivilege() {
    return <ArticleWrapper title='Reflection On Privilege' date={new Date('Jan 21, 2023')} hyphenatedTitle='reflection-on-privilege'>
        <P>Over the summer, I took a two-month course on systems dynamics with other finalists in the Rise Global Challenge. A Zoom call was held every week in which two teachers from Denmark taught us new material, and we had the chance to speak to one another in breakout rooms. One call was held in the morning (3am for me!) and one in the afternoon (1pm by my time), so there was a convenient time for both hemispheres of the world. About twenty teenagers my age from around the world joined each call. Here is a list from a Zoom screenshot of some of my classmates’ countries: Afghanistan, Denmark, Belarus, Myanmar, Nigeria, Romania, Tanzania, Zimbabwe, and Canada. In addition to learning systems dynamics, the experience of speaking one-on-one in breakout rooms with people from completely different countries and socioeconomic backgrounds was eye-opening. This call was a sample of twenty 16-year-olds from across the globe, all speaking with each other live. I talked with one girl from Myanmar, who explained that she had gone to school since elementary school, but her family was planning to leave because a government coup was posing a threat to society and replacing the current educational curriculum with propaganda. I was shocked because talking to her felt like talking to any other friend, but no friend I know has faced such a situation. There was also a well-educated boy from Tanzania I shared jokes with, who told me he was from a poor background. Talking to them, I realized that I could easily have been born in their situation. They were essentially just like me (sharing hopes, humor, and thinking) but for their situations.</P>
        <P>I quickly recognized that as a middle-class New Yorker, I was the most privileged person on the call. Our class talked a lot about climate change, and I realized I had the most power to change the climate situation and therefore had the most responsibility to do so. This revelation sparked me to write down reflections on morality and has continued to influence my thinking. I developed more empathy for and a greater understanding of people across the world. It is one thing to read news about people in third-world countries, but actually speaking with individuals one-on-one gives faces to their problems. This experience motivates me to make the world a better place for everyone, especially for those in tough situations, and makes me identify more as a global citizen. The memories of conversations tell me to care not for only myself or even for only other Americans, but for all people of the world, because although born in different places and cultures with different life circumstances and opportunities, they are just like me.</P>
    </ArticleWrapper>;
}
