POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hello world,\n\nOn November 26 of the year 12022, I hereby decree that my messages shall be protected by the power of asymmetric encryption.\n\nYours,\nJoel",
    "date": "11.26.2022",
    "signature": "Of4M9QjymkOTiIXOUTh0b6627RW082V6I12o1jitP5KvQNZoqCZ6K8C1/Z+vZSI7CvcdAYYwJ0XllxdjEQxp4w=="
}

###

POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Goodbye world,\n\nForged on November 26 of the year 12022, I hereby decree that my messages shall be protected by the power of asymmetric encryption.\n\nYours,\nJoel",
    "date": "11.26.2022",
    "signature": "Of4M9QjymkOTiIXOUTh0b6627RW082V6I12o1jitP5KvQNZoqCZ6K8C1/Z+vZSI7CvcdAYYwJ0XllxdjEQxp4w=="
}
