POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hello world,\n\nOn November 26 of the year 12022, I hereby decree that my messages shall be protected by the power of asymmetric encryption.\n\nYours,\nJoel",
    "date": "11.25.2022",
    "signature": "C0GbOSQKER6Q5b9ZdzT9gEs23nBrqgG+o1W93KYz530aKocszbnAUUr1j62s4Mr7R4Apf5WZriRb/NOm5BomFg=="
}

###

POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Goodbye world,\n\nForged on November 26 of the year 12022, I hereby decree that my messages shall be protected by the power of asymmetric encryption.\n\nYours,\nJoel",
    "date": "11.25.2022",
    "signature": "C0GbOSQKER6Q5b9ZdzT9gEs23nBrqgG+o1W93KYz530aKocszbnAUUr1j62s4Mr7R4Apf5WZriRb/NOm5BomFg=="
}
