# Should return true
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hello world!",
    "date": "11.25.2022",
    "signature": "Ab3PpddAU2oVVbuGCKTl2tRn/Nb9+UInJ3HFDKQXVerB7TMJQNBuA3ZwqKE7Oa+yMSXjZUZd8qdXKcNicop3HbCe+qg085DjH0HqujrGx+CARTh4lODTR8WW4ec5fUgl959J0LfoJfW6adVp3uWlFvec3rvLqfzCK8ZcU/k0hgwyL5CoMyb7wWhB/cEEVVg59u3LIg5cJoiBIKdqN81Y8mTOeXAVIJyPVGA++7JGJy2hm71PjFw0Xv0RCWHOU9ChtKutJiUw7UvZMVCrv1vhWiVrOHitqaGz8Z9KEw3GCp3A/oj9ODeVSoWV4QyAFFs2AHzqgI3jrieFrbfzvYELzA=="
}

###
# Should return false
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hacked message.",
    "date": "11.25.2022",
    "signature": "Ab3PpddAU2oVVbuGCKTl2tRn/Nb9+UInJ3HFDKQXVerB7TMJQNBuA3ZwqKE7Oa+yMSXjZUZd8qdXKcNicop3HbCe+qg085DjH0HqujrGx+CARTh4lODTR8WW4ec5fUgl959J0LfoJfW6adVp3uWlFvec3rvLqfzCK8ZcU/k0hgwyL5CoMyb7wWhB/cEEVVg59u3LIg5cJoiBIKdqN81Y8mTOeXAVIJyPVGA++7JGJy2hm71PjFw0Xv0RCWHOU9ChtKutJiUw7UvZMVCrv1vhWiVrOHitqaGz8Z9KEw3GCp3A/oj9ODeVSoWV4QyAFFs2AHzqgI3jrieFrbfzvYELzA=="
}

