# Should return true
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hello world!",
    "date": "11.25.2022",
    "signature": "eD36chdJBHUFllp3T6w5oMiZ0+6LRGDi/2zp9ElO/YsT+Gdwv+SsFDhYGVagnkqDSbhX7oc0QLEThkseo2Nhig=="
}

###
# Should return false
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hacked message.",
    "date": "11.25.2022",
    "signature": "eD36chdJBHUFllp3T6w5oMiZ0+6LRGDi/2zp9ElO/YsT+Gdwv+SsFDhYGVagnkqDSbhX7oc0QLEThkseo2Nhig=="
}

