# Should return true
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hello world!",
    "date": "11.25.2022",
    "signature": "U4x5N7tN1dyvukho80OqzRFG0KCLPzw8ChDI3NKcusUPF3txdLv1eGd7qDfht9wWpvVo5FSNX2bbLtq1RDDo8g=="
}

###
# Should return false
POST http://localhost:8080/verify 
Content-Type: application/json

{
    "message": "Hacked message.",
    "date": "11.25.2022",
    "signature": "U4x5N7tN1dyvukho80OqzRFG0KCLPzw8ChDI3NKcusUPF3txdLv1eGd7qDfht9wWpvVo5FSNX2bbLtq1RDDo8g=="
}

