import ArticleWrapper from '@/components/perspective/ArticleWrapper';
import { P, BU } from '@/components/perspective/writing-components';

export default function ABetterWayToTeachMath() {
    return <ArticleWrapper title='A Better Way to Teach Math' date={new Date('Feb 20, 2023')} hyphenatedTitle='a-better-way-to-teach-math'>
        <P>I believe that too often in the math curriculum, we students are taught about subjects like matrices, complex numbers, and polar coordinates without understanding the purpose. We learn the operations to perform them on tests. The problem is that without an intuitive understanding of the why, these subjects can be not only boring but also puzzling and easy to forget. Eventually, students stop asking why and just believe math is boring and not for them. When I learned about matrices in 10th grade, I was confused as to why mathematicians invented them in the first place. After being tested, I forgot how to multiply matrices, and it remained a vague concept in my brain. Later that year, I self-studied linear algebra through a geometric approach in 3Blue1Brown’s video playlist. Thinking about them geometrically let me picture them in my head and understand why they behave in certain ways intuitively (what happens when certain matrices are multiplied, what is the inverse, determinant, and eigenvalues, etc.). Only after presenting the geometric approaches did 3Blue1Brown teach the computational approaches. I believe this way of teaching is more engaging and meaningful.</P>
        <P>Matrices <BU>can</BU> be represented geometrically, but they are more fundamental than that. For this reason, matrices are often taught the more fundamental, computational way. Although the textbook definition is technically the most precise and fundamental definition, it leaves students confused. Part of the problem is that many textbook definitions are written by people who already deeply understand the concept, leading to definitions less accessible to beginners. Take a look at Wikipedia’s definition of a matrix:</P>
        <P style={{marginLeft: '4em'}} noindent>A matrix is a rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns, which is used to <BU>represent a mathematical object or a property of such an object</BU>.</P>
        <P noindent>What does “represent a mathematical object or a property of such an object” mean? I know that a matrix is a mathematical object that must satisfy certain rules, but a beginner has no idea what the rules are and why they exist. In other words, the definitions are only understood by people who already know the concept. The definition is suitable for Wikipedia, but not a learning environment. Students should be taught the geometric definition first instead of the computational definition of matrices. After they understand the geometric approach, then the teachers should explain the more fundamental nature of matrices, and that they are not based on geometry, but that geometry is a helpful way of looking at them. By starting with geometry and explaining the computation later, students will have an intuitive, visceral understanding of matrices inside out.</P>
        <P>While I have only been addressing linear algebra so far, I think this teaching method would also be useful for polar coordinates and complex numbers. Similar to matrices, I learned about complex numbers at my school before I understood why they were necessary. If students were given problems that are not solvable without complex numbers (such as basic quantum mechanics problems), they would understand their necessity. Similarly, for polar coordinates, I suggest explaining why they are helpful instead of just what they are.</P>
        <P>I understand that teachers have to cover many concepts in a limited amount of time, but I believe that it is more important to teach the why behind mathematical concepts than the how of computing with them. We have computers that can do matrix multiplication, find the determinant, or convert from polar to rectangular coordinates for us. I agree that students should be shown how to do such computations, but the real focus should be on how well they can apply the concepts. After all, math is made up; it is a human-made construct to help us solve problems. Thus, we need to make sure the next generation of problem-solvers, our students, have an intuitive understanding of  why we humans developed math the way we did. Students need to be thinking humans, ready to apply math concepts, not computing robots who merely do the same work as calculators.</P>
    </ArticleWrapper>;
}
