import ArticleWrapper from '@/components/perspective/ArticleWrapper';
import { P, BU } from '@/components/perspective/writing-components';

export default function ThankYouFossilFuels() {
    return <ArticleWrapper title='Thank You, Fossil Fuels' date={new Date('Feb 19, 2023')} hyphenatedTitle='thank-you-fossil-fuels'>
        <P>Fossil fuels have brought humanity from the 19th century to today’s modern technology. They are essential to our transportation systems, manufacturing of goods, heating during the winter, and electricity. They are necessary for the manufacturing of the computer or phone you are reading this on and chair you are sitting on, and they fuel the car you take to work. All of us should give a round of applause for fossil fuels.</P>
        <P>Fossil fuels have done their service for humanity, but now, it is time to say goodbye to them in place of better solutions. Because they are contributing to climate change, we need to convert everything that uses fossil fuels to an electric alternative or other fuel like hydrogen for energy-intensive industrial processes including manufacturing. Doing so will create many new jobs, but we need to make sure nobody is left behind. The oil worker whose family is barely paying their rent will need to get a job at a nuclear power plant, utility, or solar company, where they would have better pay and a higher quality of life. Even fossil fuel company administrators and CEOs could transition to alternative energy following Ørsted’s example to ensure their company not only survives but grows. We need to have a peaceful transition, not a polarized culture war where Greta’s supporters accuse people who support fossil fuels as monsters and fossil fuel CEOs downplay climate change or inaccurately greenwash their companies.</P>
        <P>So thank you for all you have done, fossil fuels. It is time to move on. It’s time to come together as humanity to solve this problem, not to blame and pull each other apart.</P>
    </ArticleWrapper>;
}
