import ArticleWrapper from '@/components/perspective/ArticleWrapper';
import { Citation, Footnote, BU, P, H2, TeX } from '@jcomponents/writing-components';
import Image from 'next/image';
import Link from 'next/link';

export default function WhyWeNeedNuclearEnergy() {
    return <ArticleWrapper title='Why We Need Nuclear Energy' date={new Date('May 9, 2021')} hyphenatedTitle='why-we-need-nuclear-energy'>
        <P>Since students face the consequences of climate change now and increasingly as we grow up, I urge Riverdalians to consider solutions in battling climate change. Given American nuclear energy’s stagnation in the last three decades and low public trust, I hope students learn that employing nuclear energy is one of the <BU>best strategies to save millions of lives from pollution, lower carbon emissions all while boosting the economy.</BU> I have divided this article into three sections: nuclear energy’s benefits, costs, and solutions.</P>
        
        <H2>Benefits</H2>
        <P>For many people, the sound of “nuclear” instigates feelings of danger or fear; its low public support causes reactors to close. Since 1996, only one reactor has been built in the U.S. out of the existing 94 and some are closing. For example, 25 miles north of Riverdale, two reactors at Indian Point are being dismantled. Protests and insufficient funding cause these reactors to close. A 2016 Gallup poll revealed 54% of Americans opposed nuclear energy.<Citation number='1' /> Many people associate nuclear energy with nuclear weapons, and the meltdowns in Chernobyl, Fukushima, and Three Mile Island. Furthermore, the media often focuses on disasters and radioactivity, influencing people’s risk perception around the safety of modern reactors.</P>
        <Image src='/image/perspective/why-we-need-nuclear-energy/nuclear-death-rates.png' alt='nuclear-death-rates' height='278' width='330' style={{ float: 'right', marginRight: 30 }} />
        <P>Despite its reputation, nuclear energy is arguably the <BU>safest energy source</BU> saving the most human lives without harming nature. The following graph shows how many deaths are caused by accidents and air pollution for every thousand terawatt-hours, a unit of energy. As you can see, while coal, oil, and gas cause 100,000, 36,000, and 4,000 deaths respectively, nuclear pales in comparison at only 90 deaths. Even wind and solar cause more deaths per thousand terawatt-hours than nuclear. How do the other sources cause deaths? In addition to emitting CO₂, fossil fuels emit toxic fine particles into the air, which we breathe. This inhaled poison causes 4 million annual deaths from lung cancer, stroke, heart disease, etc. Hydropower dams can breach, flooding entire communities. The Banqiao hydropower dam failure destroyed seven million houses and killed 26,000-250,000 lives.<Citation number='2' /> On a smaller scale, solar panels contain toxic heavy metals (lead and cadmium) contaminating the soil and local environment, and wind turbines are dangerous to assemble. If these other energy sources cause considerable deaths, how come nuclear energy generation causes so few deaths? By contrast, the majority of nuclear energy is controlled robotically, protecting employees, and reactors can run smoothly for years without requiring maintenance. Recent studies show that working at a power plant is safer than a city office because workers are not exposed to high levels of radiation.<Citation number='3' /> Additionally, the myth that living by a nuclear reactor exposes you to radiation is false: only a negligible 0.005% of people’s annual radiation dosage comes from nuclear energy.<Citation number='4' /> For these reasons, researchers at the American Chemical Society calculated that <BU>nuclear energy from 1971-2009 prevented 1.9 million deaths</BU> from air pollution alone.<Citation number='5' /></P>
        <div className='grid place-items-center my-3'>
            <Image src="/image/perspective/why-we-need-nuclear-energy/France vs Brazil's Electricity Sources.png" alt="France vs Brazil's Electricity Sources" height='225' width='640' />
        </div>
        <P>In terms of the environment, nuclear energy is a low-carbon solution to fossil fuels.<Citation number='6' /> The two developed countries with the lowest carbon emissions per capita are France and Sweden. France’s low emissions are credited to the fact that 70% of its electricity comes from nuclear, and Sweden 40%. If you look at the graph of French electricity sources, you can see nuclear (yellow) prevents oil, gas, and coal from growing past 9%. Without nuclear energy, the renewable alternatives would have difficulty scaling up, so the energy void would be filled by fossil fuels. Brazil demonstrates that <BU>without nuclear energy, fossil fuels fill the gap</BU>, by relying 55% on fossil fuels as shown in the chart.</P>
        <P>Implementing <BU>renewable solar and wind power without nuclear energy will not lower carbon emissions</BU> enough and will aid the fossil fuel industry with secured demand. Although wind and solar energy do not emit CO2, their energy output is extremely volatile. On sunny days, solar produces more energy than on a cloudy day and does not produce any energy at night. Unless society stores massive amounts of energy accumulated from solar to use when it is not sunny, which is difficult and expensive, this volatility means other energy sources need to quickly scale up and down to meet demand. At the moment, fossil fuels are the only solution to accommodate when renewable energy output is low. For this reason, fossil fuel industries such as Total are promoting solar because it ensures we will rely on fossil fuels.</P>
        <P>Nuclear energy also produces consistent amounts of energy, can run anywhere and anytime regardless of the weather, and creates more jobs than its energy alternatives. It has the highest capacity factor out of all energy sources at 93%, meaning it produces full power 93% of the time compared to solar voltaic at 25%, wind at 35%, and natural gas at 14%.<Citation number='7' /></P>

        <H2>Costs</H2>
        <Image src='/image/perspective/why-we-need-nuclear-energy/Nuclear vs. Gas Power Plant Profits (1000 MWe).jpg' alt='Nuclear vs. Gas Power Plant Profits (1000 MWe)' height='278' width='330' style={{ float: 'right', marginLeft: 30 }} />
        <P><BU>Short-term economic thinking explains the lack of more nuclear plants. Compare the economics of building a 1000-megawatt natural gas plant versus a 1000-megawatt nuclear power plant</BU>.<Citation number='8' /> Both plants produce the same thousand megawatts of electricity to supply around one million homes in the Northeast. Their biggest differences are price, construction time, and fuel cost. Building a nuclear power plant requires 5-9 billion dollars and six years to construct, while a natural gas plant only needs 0.9 billion dollars and two years. As you can see in the diagram, the nuclear power plant takes out a 25-year 6 billion-dollar loan and climbs into a steep 15-billion dollar debt in the first six years (from interest) while the natural gas plant is constructed quickly and starts making profits within five years. However, once the power plant is complete, it produces electricity most cheaply due to uranium fuel prices costing less than natural gas. For this reason, nuclear has a steeper upward slope and eventually surpasses natural gas in profits at year 17. In year 25, the loans are fully paid, and since the nuclear power plant borrowed six-fold more to build than the natural gas plant, its profits increase substantially more than oil does after paying off its loans. With patience, nuclear power plants make more economic sense by producing cheaper electricity. However, there is high initial risk when building a nuclear power plant because of the massive loans. If there are delays from funding shortages or protests, debt can enlarge such as in the five-year delay of the Vogtle nuclear power plant, which ramped up the cost to 12.5 billion dollars per reactor. Many politicians are unwilling to face the initial risk or lack the motivation to start a project that will not be profitable during their term in office, and investors desire immediate returns over greater long-term profits.</P>
        
        <H2>Solutions</H2>
        <P>Nuclear energy has important benefits, but its reputation and construction cost, time, and risk hinder the production of more plants, so society should invest in small modular reactors. Small Modular Reactors (SMRs), now being developed, produce below 300 megawatts of electricity, smaller than the current big reactors in the thousands of megawatts. Unlike the bigger reactors, which require many years and billions of dollars to build on site and require a unique installation at each location (in the U.S.), SMRs could be mass-produced and shipped inside trucks or airplanes. SMRs come with fuel and never need to be opened. SMRs can run independent of the power grid, making them excellent for remote areas and buildings that require electricity at all times. Rural areas not connected to the power grid that currently rely on fossil fuels could employ SMRs as a clean alternative. During power grid failure disasters, SMRs as backups can power important buildings such as hospitals, data centers, and military bases. SMRs will likely be available by 2030 or earlier in the U.S., and one is currently being built in Canada that will finish in 2024. When these SMRs are available, facilities such as Riverdale could purchase and connect an SMR to their microgrids to make campus carbon-neutral.</P>
        <P>In addition to SMRs, society should fund more research into thorium and fusion reactors due to their potential to start new energy revolutions. Uranium is not renewable, and supplies will run out in 200 years if we do not continue to innovate. Thorium, on the other hand, is three times as abundant, and almost completely fertile, meaning we can use most of the mined thorium to generate energy, compared to only using less than 1% of mined uranium.</P>
        <P>What can we do? Stay informed. Nuclear is one of the most misunderstood energy sources, and fear without logic has steered the public away from it. Environmental advocates have often mistakenly criticized nuclear energy in counterproductive ways. To fight disinformation, form your nuclear energy opinions based on scientific research and studies, instead of irrational fear.</P>
        <br /><br />
        
        <div> {/* Footnotes */}
            <Footnote number='1'>
                <i>For First Time, Majority in U.S. Oppose Nuclear Energy. (n.d.). Retrieved May 27, 2021, from <Link className='styled' href='https://news.gallup.com/poll/190064/first-time-majority-oppose-nuclear-energy.aspx'>https://news.gallup.com/poll/190064/first-time-majority-oppose-nuclear-energy.aspx</Link></i>
            </Footnote>
            <Footnote number='2'>
                <i>Lessons from catastrophic dam failures in August 1975 in Zhumadian, China—HKUST SPD | The Institutional Repository.</i> (n.d.). Retrieved May 27, 2021, from <Link href='https://repository.ust.hk/ir/Record/1783.1-20080' className='styled'>https://repository.ust.hk/ir/Record/1783.1-20080</Link>
            </Footnote>
            <Footnote number='3'>Nuclear Energy Institute (NEI)</Footnote>
            <Footnote number='4'> National Council on Radiation Protection and Measurements</Footnote>
            <Footnote number='5'>Prevented Mortality and Greenhouse Gas Emissions from Historical and Projected Nuclear Power | Environmental Science & Technology <Link href='https://pubs.acs.org/doi/abs/10.1021/es3051197' className='styled'>https://pubs.acs.org/doi/abs/10.1021/es3051197</Link> (accessed May 27, 2021).</Footnote>
            <Footnote number='6'>Note: mining uranium alters the environment, but the reactors themselves do not.</Footnote>
            <Footnote number='7'><i>U.S. energy capacity factors by source 2020 | Statista.</i> (n.d.). Retrieved May 27, 2021, from <Link href='https://www.statista.com/statistics/183680/' className='styled'>https://www.statista.com/statistics/183680/us-average-capacity-factors-by-selected-energy-source-since-1998/</Link></Footnote>
            <Footnote number='8'>Data from the Illinois Energy Professor&apos;s calculations.</Footnote>
        </div>
    </ArticleWrapper>;
}
